name: Upload Photo Journal

on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.1
      with:
        provider: linode # default is linode
        region: 'us-east-1'
        access_key: ${{ secrets.S3_ACCESS_KEY }}
        secret_key: ${{ secrets.S3_SECRET_KEY }}
    - name: Interact with object storage
      run: |
        s3cmd --no-mime-magic --acl-public --delete-removed --delete-after sync public/ s3://photo-journal
        s3cmd info s3://photo-journal